@SoftwareEngineerSkills.API_HostAddress = http://localhost:5096

// Dummy Controller - Get All Dummies
GET {{SoftwareEngineerSkills.API_HostAddress}}/api/dummy
Accept: application/json

###

// Dummy Controller - Get All Dummies (including inactive)
GET {{SoftwareEngineerSkills.API_HostAddress}}/api/dummy?includeInactive=true
Accept: application/json

###

// Dummy Controller - Get Dummy by ID
// Replace {id} with an actual Dummy ID
GET {{SoftwareEngineerSkills.API_HostAddress}}/api/dummy/00000000-0000-0000-0000-000000000000
Accept: application/json

###

// Dummy Controller - Create New Dummy
POST {{SoftwareEngineerSkills.API_HostAddress}}/api/dummy
Content-Type: application/json
Accept: application/json

{
  "name": "Test Dummy",
  "description": "This is a test dummy created via HTTP request",
  "priority": 3
}

###

// Dummy Controller - Update Dummy
// Replace {id} with an actual Dummy ID
PUT {{SoftwareEngineerSkills.API_HostAddress}}/api/dummy/00000000-0000-0000-0000-000000000000
Content-Type: application/json
Accept: application/json

{
  "id": "00000000-0000-0000-0000-000000000000",
  "name": "Updated Dummy",
  "description": "This dummy has been updated",
  "priority": 4
}

###

// Dummy Controller - Delete Dummy
// Replace {id} with an actual Dummy ID
DELETE {{SoftwareEngineerSkills.API_HostAddress}}/api/dummy/00000000-0000-0000-0000-000000000000
Accept: application/json

###

// Dummy Controller - Activate Dummy
// Replace {id} with an actual Dummy ID
PATCH {{SoftwareEngineerSkills.API_HostAddress}}/api/dummy/00000000-0000-0000-0000-000000000000/activate
Accept: application/json

###

// Dummy Controller - Deactivate Dummy
// Replace {id} with an actual Dummy ID
PATCH {{SoftwareEngineerSkills.API_HostAddress}}/api/dummy/00000000-0000-0000-0000-000000000000/deactivate
Accept: application/json

###
